### ISSUE TITLE
Processing Spiral Scans as Energy Scans

### ISSUE THREAD

**Issue by ESteissberg** [EliotGann/Eliots-NIKA#10]
The current implementation resets the input energy to NaN while trying to convert positional scans, which happen to lack the appropriately labeled metadata for Xray energy. If possible, please modify either the code or the metadata to include energy as if a positional scan is an energy scan. The energy is in the position scan metadata but labeled differently, so this may be a side effect of a solution to other problems?

**Comment by EliotGann** [comment]
Fixed with 51ba537
